//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public string Address_Street_1 { get; set; }
        public string Address_Street_2 { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public Nullable<int> Zip_PostalCode { get; set; }
        public Nullable<int> Home_Telephone { get; set; }
        public Nullable<int> Mobile { get; set; }
        public Nullable<int> Work_Telephone { get; set; }
        public string State_Province { get; set; }
        public string Work_Email { get; set; }
        public string Other_Email { get; set; }
    }
}
