//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomField
    {
        public int Id { get; set; }
        public int CustomFieldId { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<bool> Required { get; set; }
        public Nullable<bool> has_list { get; set; }
        public string listvalues { get; set; }
        public string Value { get; set; }
        public string type { get; set; }
        public byte[] blob { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> IsCondition { get; set; }
        public Nullable<int> ParentCutomFieldId { get; set; }
        public string ParentCustomFieldValue { get; set; }
    }
}
