//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectDeposit
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Account_Number { get; set; }
        public string Finaicial_Institute { get; set; }
        public string Account_Type { get; set; }
        public string Branch_Location { get; set; }
        public Nullable<int> Routing_Number { get; set; }
    }
}
