//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMembership
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public string Membership { get; set; }
        public string Subscription_PaidBy { get; set; }
        public Nullable<decimal> Currency { get; set; }
        public Nullable<System.DateTime> Subscription_Renewal_Date { get; set; }
        public Nullable<System.DateTime> Subscription_Commence_Date { get; set; }
        public Nullable<decimal> Subscription_Amount { get; set; }
    }
}
