//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJob
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> Joined_Date { get; set; }
        public Nullable<System.DateTime> Probation_End_Date { get; set; }
        public Nullable<System.DateTime> Date_Of_Permanency { get; set; }
        public string Job_Title { get; set; }
        public string Employment_Status { get; set; }
        public string Job_Category { get; set; }
        public string Sub_Unit { get; set; }
        public string Work_Shift { get; set; }
        public Nullable<System.DateTime> Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> Contract_End_Date { get; set; }
        public string Cost_Center { get; set; }
        public string FLSA_Exempt { get; set; }
        public string EEO_Job_Category { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Effective_From { get; set; }
        public string Job_Specification { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
