//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeCurrency
    {
        public int Id { get; set; }
        public int PayGradeId { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> MinimumSalary { get; set; }
        public Nullable<decimal> MaximumSalary { get; set; }
    }
}
