//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Immigration
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public string Document { get; set; }
        public Nullable<int> Number { get; set; }
        public string Eligible_Status { get; set; }
        public string Issued_By { get; set; }
        public Nullable<System.DateTime> Issued_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<System.DateTime> Eligible_Review_Date { get; set; }
        public string Comment { get; set; }
    }
}
