//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDetail
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Employee_Id { get; set; }
        public string Other_Id { get; set; }
        public Nullable<System.DateTime> Date_Of_Birth { get; set; }
        public string Marital_Status { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Drivers_License_Number { get; set; }
        public Nullable<System.DateTime> License_Expiry_Date { get; set; }
        public string EEO_Race_And_Ethnicity { get; set; }
        public string Smoker { get; set; }
        public string Military_Service { get; set; }
        public string Nick_Name { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
