//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleTypeWorkflowManagement
    {
        public int RoleTypeWorkflowManagementId { get; set; }
        public Nullable<int> RoleTypeId { get; set; }
        public Nullable<int> WorkflowManagementId { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual WorkflowManagement WorkflowManagement { get; set; }
    }
}
