//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDataGroupPermission
    {
        public int RoleDataGroupId { get; set; }
        public int RoleId { get; set; }
        public int DataGroupPermissionId { get; set; }
    
        public virtual DataGroupPermission DataGroupPermission { get; set; }
        public virtual Role Role { get; set; }
    }
}
