//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> Effective_From { get; set; }
        public Nullable<int> Paygrade { get; set; }
        public Nullable<decimal> Currency { get; set; }
        public Nullable<decimal> Annual_Basic_Payment { get; set; }
        public string EEO_PayBand { get; set; }
        public string Comments { get; set; }
    }
}
