//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryComponent
    {
        public long SalaryComponentId { get; set; }
        public string Name { get; set; }
        public bool Earning { get; set; }
        public bool Deduction { get; set; }
        public bool TotalPayable { get; set; }
        public bool CostToCompany { get; set; }
        public bool Amount { get; set; }
        public bool Percentage { get; set; }
        public Nullable<long> OrganizationId { get; set; }
    }
}
