//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionField
    {
        public int Id { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
        public bool Required { get; set; }
        public bool Available { get; set; }
        public Nullable<int> Type { get; set; }
        public string ListOptions { get; set; }
        public string Value { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
