//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRegion
    {
        public long UserRegionId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> RegionId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual User User { get; set; }
    }
}
