//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkExperience
    {
        public int Id { get; set; }
        public int OrganisationId { get; set; }
        public int EmployeeId { get; set; }
        public string Company { get; set; }
        public string Job_Title { get; set; }
        public Nullable<System.DateTime> From { get; set; }
        public Nullable<System.DateTime> To { get; set; }
        public string Creditable { get; set; }
        public string Comment { get; set; }
    }
}
